### ISSUE TITLE
"afh" added to BepInEx log everytime I speak, but no actions happen

### ISSUE THREAD

**Issue by DaddyBoard** [LoafOrc/ShipVoiceCommands#1]
"afh" added to BepInEx log everytime I speak, but no actions happen. 

I am religiously trying to get this to work, I have tested my voice recognition in Phasmophobia and it works just fine, which I believe uses the Microsoft voice recognition aswell.

I'm a techy so know all the troubleshooting and it simply will not work

**Comment by LoafOrc** [comment]
This is a dumb issue I accidently caused. Making sure you use version 1.0.1 of VoiceRecognitionAPI should fix the problem.
